### ISSUE TITLE
groopsio import fails

### ISSUE THREAD

**Issue by AndreHauschild** [groops-devs/groopsio#10]
Hello groops team,

I have encountered a problem today when trying to use the groopsio package. Importing the module fails with the following error:

```
Traceback (most recent call last):
  File "/home/user/Software/groopsio/test.py", line 2, in <module>
    import groopsio.io as gio
  File "/home/user/Software/groopsio/groopsio/__init__.py", line 25, in <module>
    from . import io
  File "/home/user/Software/groopsio/groopsio/io.py", line 22, in <module>
    import groopsiobase as giocpp
ImportError: /home/user/.local/lib/python3.10/site-packages/groopsiobase.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTI19PlatformGnssAntenna
```

I am on an Ubuntu 22.04.1 LTS with Python 3.10.6 and pip 22.0.2. I am using a fresh clone of groops and the installation with 
```
GROOPS_SOURCE_DIR=/home/user/Software/groops.orig/source/ pip install .
```
works without errors. Any ideas what could be wrong? Please let me know if you need additional information. Thanks!

**Comment by zhedumi** [comment]
Hi,

Yeah I had that issue and fixed it in my forked groopsio. I currently made a pull request for this https://github.com/groops-devs/groopsio/pull/11#issue-1713671100 . 
The issue is basically that the new filePlatform is probably not updated within your groopsio. The easy dirty fix is to include it in sources.list and within groopsio.h . Otherwise it might take some time till the pull request is merged to the master including this update.

best regards,
Patrick

**Comment by AndreHauschild** [comment]
Excellent, that did it. Thanks for you help!
